# Disable the blank line at the start of the prompt
add_newline = false

# palette = 'gruvbox'
#
# [palettes.gruvbox]
#

format = """
[ ](bg:#d5c4a1)\
$os\
$username\
$hostname\
[](bg:#7c6f64 fg:#d5c4a1)\
$directory\
[](fg:#7c6f64 bg:#504945)\
$git_branch\
$git_status\
[](fg:#504945 bg:#282828)\
$time\
[](fg:#282828 bg:#1d2021)\
[](fg:#1d2021)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#d5c4a1 fg:#1d2021"
style_root = "bg:#d5c4a1 fg:#cc241d"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = "bg:#d5c4a1 fg:#282828"
format = '[$ssh_symbol]($style)[@]($style)[$hostname ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#7c6f64 fg:#fbf1c7"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#504945 fg:#8ec07c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#504945 fg:#fabd2f"
# $all_status==$conflicted$stashed$deleted$renamed$modified$staged$untracked
format = '[$conflicted](bg:#504945 fg:#fb4934)[$stashed](bg:#504945 fg:#d3869b)[$deleted](bg:#504945 fg:#cc241d)[$renamed](bg:#504945 fg:#fabd2f)[$modified](bg:#504945 fg:#fe8019)[$staged](bg:#504945 fg:#b8bb26)[$untracked](bg:#504945 fg:#458588)[$ahead_behind]($style)'

[golang]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
disabled = true
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#282828"
format = '[  $time ]($style)'
